spring.application.name=shop-management-system
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop_management_system}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
# WARNING: Set to 'create' for SaaS migration (Wipes DB). Change back to 'validate' or 'update' after deploy!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

# JWT Configuration
app.jwtSecret=WyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJzaG9wLW1hbmFnZW1lbnQtc3lzdGVtIiwiY29udGV4dCI6InByb2R1Y3Rpb24ifQ==
app.jwtExpirationMs=86400000
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true